// TVoxar IPTV - Configuration & Site Metadata
// Production Domain: https://www.tvoxar.top/

export const siteConfig = {
  name: "TVoxar",
  brandName: "TVoxar IPTV",
  domain: "https://www.tvoxar.top",
  tagline: "Next-Generation Premium IPTV Streaming Service",
  description:
    "Experience seamless ultra-high-definition television entertainment with TVoxar IPTV. Access thousands of premium live channels, worldwide sports tournaments, and expansive on-demand video libraries with cutting-edge Anti-Freeze 9.3 streaming technology.",
  supportEmail: "support@tvoxar.top", // Configurable support placeholder
  supportHours: "24/7 Priority Support",
  whatsapp: "+1 (Configurable Placeholder)", // Configurable placeholder
  telegram: "@TVoxarOfficial", // Configurable placeholder
  
  // Navigation structure
  navLinks: [
    { label: "Home", href: "/" },
    { label: "Subscription Plans", href: "/pricing" },
    { label: "Features", href: "/features" },
    { label: "Devices", href: "/devices" },
    { label: "Channels", href: "/channels" },
    { label: "Installation Guides", href: "/installation" },
    { label: "FAQ", href: "/faq" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
  ],

  // Pricing plans (Configurable pricing tiers)
  pricingPlans: [
    {
      id: "1-month",
      name: "1-Month Pass",
      duration: "1 Month",
      price: "$14.99",
      billingPeriod: "one-time payment",
      popular: false,
      badge: "Starter",
      description: "Ideal for testing TVoxar IPTV stream stability, channel switching speed, and live sports on your primary device.",
      features: [
        "Full access to premium HD & 4K channels",
        "Comprehensive sports & pay-per-view coverage",
        "Complete VOD movies & series library",
        "TVoxar Anti-Freeze 9.3 stream protocol",
        "Electronic Program Guide (EPG)",
        "Fast automated credential delivery",
        "1 Simultaneous Screen connection",
        "24/7 technical customer support",
      ],
      ctaText: "Order 1-Month IPTV Plan",
      checkoutUrl: "/contact?plan=1-month",
    },
    {
      id: "3-month",
      name: "3-Month Pass",
      duration: "3 Months",
      price: "$34.99",
      billingPeriod: "one-time payment",
      popular: false,
      badge: "Quarterly",
      description: "The optimal IPTV choice for ongoing sports seasons, regular weekend tournaments, and continuous cinema streaming.",
      features: [
        "Full access to premium HD & 4K channels",
        "All live sports, tournaments & PPV events",
        "VOD movies & binge-worthy series updated weekly",
        "TVoxar Anti-Freeze 9.3 stream protocol",
        "Fast-loading 7-day EPG guide",
        "Fast automated credential delivery",
        "1 Simultaneous Screen connection",
        "Priority 24/7 support assistance",
      ],
      ctaText: "Order 3-Month IPTV Plan",
      checkoutUrl: "/contact?plan=3-month",
    },
    {
      id: "6-month",
      name: "6-Month Pass",
      duration: "6 Months",
      price: "$49.99",
      billingPeriod: "one-time payment",
      popular: true,
      badge: "Most Popular",
      description: "Exceptional balance of extended uninterrupted entertainment, priority server access, and best overall value.",
      features: [
        "Full access to premium HD & 4K channels",
        "Unrestricted access to all live sports & PPVs",
        "Massive VOD archive with multi-language audio",
        "TVoxar Anti-Freeze 9.3 stream protocol",
        "Interactive 7-day EPG guide with catchup",
        "Instant delivery via email & dashboard",
        "1 Simultaneous Screen connection",
        "Priority VIP support channel",
        "Free device reconfiguration assistance",
      ],
      ctaText: "Order 6-Month IPTV Plan",
      checkoutUrl: "/contact?plan=6-month",
    },
    {
      id: "12-month",
      name: "12-Month VIP Pass",
      duration: "12 Months",
      price: "$69.99",
      billingPeriod: "one-time payment",
      popular: false,
      badge: "Best Value",
      description: "Complete year-round TVoxar IPTV entertainment pass with VIP edge-server routing, full 4K catalog, and priority account care.",
      features: [
        "Full access to premium HD & 4K channels",
        "All major league sports, football, racing & PPV",
        "VOD cinema catalog with 4K UHD titles",
        "TVoxar Anti-Freeze 9.3 priority server tier",
        "Comprehensive 7-day EPG with catchup",
        "Instant automated activation",
        "1 Simultaneous Screen connection",
        "24/7 VIP Dedicated Account Manager",
        "Free setup assistance for all your devices",
        "7-Day Satisfaction Guarantee",
      ],
      ctaText: "Order 12-Month VIP Plan",
      checkoutUrl: "/contact?plan=12-month",
    },
  ],

  // Supported devices
  supportedDevices: [
    {
      slug: "firestick",
      name: "Amazon Fire TV Stick",
      icon: "Flame",
      subtitle: "Firestick 4K, 4K Max, Cube & Fire TV Edition",
      description: "Quick setup with TiviMate, Downloader, and IPTV Smarters Pro apps on Amazon Fire OS.",
      guideHref: "/installation/firestick",
      recommendedApp: "TiviMate / IPTV Smarters Pro",
    },
    {
      slug: "samsung-lg-smart-tv",
      name: "Samsung & LG Smart TV",
      icon: "Tv",
      subtitle: "Samsung Tizen OS & LG webOS TVs",
      description: "Direct IPTV streaming via native app store players like IBO Player Pro, Smart IPTV, and Nanomid.",
      guideHref: "/installation/samsung-lg-smart-tv",
      recommendedApp: "IBO Player Pro / Smart IPTV",
    },
    {
      slug: "android",
      name: "Android TV & Mobile",
      icon: "Smartphone",
      subtitle: "Google TV, Nvidia Shield, Sony, Xiaomi & Phones",
      description: "Full Google Play store compatibility with leading IPTV apps like TiviMate and OTT Navigator.",
      guideHref: "/installation/android",
      recommendedApp: "TiviMate / OTT Navigator",
    },
    {
      slug: "apple-tv-ios",
      name: "Apple TV, iPhone & iPad",
      icon: "Apple",
      subtitle: "tvOS, iOS, and iPadOS devices",
      description: "High-performance tvOS & iOS streaming using IPTVX, GSE Smart IPTV, or Smarters Player on the App Store.",
      guideHref: "/installation/apple-tv-ios",
      recommendedApp: "IPTVX / GSE Smart IPTV",
    },
    {
      slug: "windows-mac",
      name: "Windows PC & Mac",
      icon: "Monitor",
      subtitle: "Windows 10/11 & macOS laptops and desktops",
      description: "Stream TVoxar IPTV on your computer using IPTV Smarters Pro Desktop, VLC Media Player, or Web Player.",
      guideHref: "/installation/windows-mac",
      recommendedApp: "IPTV Smarters Desktop / VLC",
    },
    {
      slug: "mag-box",
      name: "MAG Box & STB Emulator",
      icon: "Box",
      subtitle: "Infomir MAG 250, 322, 421, 524 & STB Emulator",
      description: "Classic STB portal URL integration using your hardware MAC address for dedicated set-top box streaming.",
      guideHref: "/installation/mag-box",
      recommendedApp: "Internal Portal / STB Emulator",
    },
    {
      slug: "formuler-box",
      name: "Formuler Z Series",
      icon: "Radio",
      subtitle: "Formuler Z8, Z10, Z11 & CC boxes",
      description: "Optimized integration with MYTVOnline 2 and MYTVOnline 3 for lightning-fast channel zapping.",
      guideHref: "/installation/formuler-box",
      recommendedApp: "MYTVOnline 2 & 3",
    },
    {
      slug: "roku",
      name: "Roku TV & Streaming Stick",
      icon: "Cast",
      subtitle: "Roku OS, TCL Roku & Express devices",
      description: "Smart screen-mirroring and casting methods to stream TVoxar IPTV channels on Roku displays.",
      guideHref: "/installation/roku",
      recommendedApp: "AirPlay / Screen Cast",
    },
  ],

  // Common FAQ items
  faqs: [
    {
      q: "What is TVoxar and how does the streaming service work?",
      a: "TVoxar is a modern digital streaming platform delivering live television channels, sports broadcasts, and an extensive video-on-demand library directly over your internet connection. Instead of traditional satellite dishes or cable subscriptions, TVoxar streams content to your television, media stick, phone, or computer via modern IPTV applications.",
      category: "General",
      linkHref: "/features",
      linkText: "Explore TVoxar streaming features →",
    },
    {
      q: "How fast does my internet connection need to be?",
      a: "For smooth High Definition (HD) streaming, a stable broadband connection of at least 15 Mbps is recommended. For uninterrupted 4K Ultra HD and 60fps live sports broadcasts, a dedicated speed of 30 Mbps or higher guarantees the best buffer-free experience.",
      category: "Technical",
      linkHref: "/blog/fix-iptv-buffering-freezing-guide",
      linkText: "Read our buffering troubleshooting guide →",
    },
    {
      q: "Do I need a satellite dish or special cable to use TVoxar?",
      a: "No physical satellite dish or cable wiring is required. TVoxar functions entirely over high-speed internet. All you need is a compatible smart screen, media streamer (such as Fire TV Stick or Apple TV), or mobile device with a supported IPTV application.",
      category: "General",
      linkHref: "/devices",
      linkText: "Browse all compatible devices & setups →",
    },
    {
      q: "How quickly are my login credentials delivered after subscribing?",
      a: "Account activation is handled automatically. Once your order is confirmed, your M3U playlist URL, Xtream Codes credentials (server URL, username, and password), and step-by-step setup instructions are dispatched to your provided contact details within minutes.",
      category: "Subscription",
      linkHref: "/pricing",
      linkText: "Compare plans with instant delivery →",
    },
    {
      q: "Can I watch TVoxar on multiple devices simultaneously?",
      a: "Standard passes are configured for 1 active stream connection at any single moment. You can install your account credentials on multiple devices (for instance, living room TV and smartphone), but they should not be played at the exact same time unless you select a multi-screen subscription package.",
      category: "Subscription",
      linkHref: "/pricing",
      linkText: "Check multi-room subscription tiers →",
    },
    {
      q: "Do I need to use a VPN with TVoxar?",
      a: "TVoxar works seamlessly both with and without a VPN. If your local internet service provider engages in bandwidth throttling during high-demand live sporting events, utilizing a reliable VPN (such as NordVPN, ExpressVPN, or Surfshark) can bypass ISP limits and ensure optimal throughput.",
      category: "Technical",
      linkHref: "/blog/best-vpn-for-iptv-streaming-guide",
      linkText: "See recommended VPNs for IPTV in 2026 →",
    },
    {
      q: "What is TVoxar Anti-Freeze 9.3 technology?",
      a: "TVoxar utilizes dynamic load balancing and adaptive bitrate compression protocols across distributed edge servers. When network congestion occurs, our servers automatically adjust data packet transmission to prevent buffering, audio desynchronization, and video freezing.",
      category: "Technical",
      linkHref: "/features",
      linkText: "Learn more about Anti-Freeze 9.3 technology →",
    },
    {
      q: "What payment methods are supported on TVoxar?",
      a: "TVoxar supports secure payment channels including major credit/debit cards, PayPal, and leading cryptocurrency payment gateways. All transactions are protected by industry-standard SSL encryption.",
      category: "Subscription",
      linkHref: "/contact",
      linkText: "Need payment assistance? Contact support →",
    },
    {
      q: "What is your refund policy?",
      a: "We want every customer to be confident in our streaming quality. If you experience verified technical setup difficulties that our 24/7 technical team cannot resolve within your first 7 days of service, you are entitled to request a refund according to our transparent Refund Policy.",
      category: "Subscription",
      linkHref: "/refund-policy",
      linkText: "Read our complete 7-day refund guarantee →",
    },
  ],
};
